### ISSUE TITLE
Errors in mds.py

### ISSUE THREAD

**Issue by pedestrian0423** [LCAV/pylocus#19]
I having a problem in running pylocus for my localization program.
It seems to be f is not defined and used in the function 'x_from_eigendecomp' in mds.py 

However, with the revision 9a322e455f0ffbc6e8e77e3e5b3e540b46e02d65, my code works fine.

Here is an error message.
`  File "d:\code\pylocus\pylocus\algorithms.py", line 9, in execute_method
    noisy_edm, real_points=real_points, method='geometric')
  File "d:\code\pylocus\pylocus\algorithms.py", line 176, in reconstruct_mds
    Xhat = MDS(edm, d, method, False).T
  File "d:\code\pylocus\pylocus\mds.py", line 48, in MDS
    return x_from_eigendecomp(factor, u, dim)
  File "d:\code\pylocus\pylocus\mds.py", line 19, in x_from_eigendecomp
    return ((f * u).T)[:dim, :]
NameError: name 'f' is not defined`

**Comment by duembgen** [comment]
Thank you for pointing this out. Are you using the pip version or the latest github version?

**Comment by pedestrian0423** [comment]
Thanks for the reply.
I tried to use latest github version of pylocus, with python 3.6.5.

**Comment by duembgen** [comment]
@pedestrian0423, this was a typo introduced by a different pull request it seems. I am setting up continuous integration right now such that things like this do not happen in the future. Thank you for your help!
